//ACCOUNTING.cpp
//Member-function definitions for class ACCOUNTING
#include "ACCOUNTING.h"//ACCOUNTING class definition
#include <iostream>
#include <fstream>
#include <string>

//ACCOUNTING default constructor initializes data member
ACCOUNTING::ACCOUNTING()
  : userAuthenticated(false) //user is not authenticated to start
  {
    //empty body
  }// end ACCOUNTING default constructor

  // start runnning ACCOUTNING
  void ACCOUNTING::run()
  {
      controller.read();
      // loop while user is not yet authenticated
      while(!userAuthenticated)
      {
        std::cout << "Accounting system is initiated, pls type in Accounting number and PIN\n";
        authenticate();// user will be authenticated if pin matches the database
      }
      bool exitedUser = false;// user does not comfirm the exitting.
      while(!exitedUser)
      {
        // displaying the main menu
        std::cout<<"\nMain menu:\n" << " OPEN - Open an account\n"
        << " DEPOSIT - Deposit money\n" << " WITHDRAW - Withdraw money\n" << " PURCHASE - Purchase at a POS\n TIME - Attempt to a time deposit\n"
        << " TRANSFER - Transfer\n SETTLE - Settle interests \n CLOSE - delete account \n BALANCE - quiry the balance \n EXIT - Exit the system\n";
        std::string customerInput;
        std::cin >> customerInput;

        // since stwich command support integer only, but in this system we insist the user to type in string command.
        // open a new account number
        if( customerInput == "OPEN")
        {
            std::cout << "Open an account:\nPlease enter customer identity\n";
            std::string KYC; std::cin >> KYC;
            std::cout<<"Please set up your 6-digit password PIN\n";
            std::string PIN; std::cin >> PIN;
            // check whether user has set a six-digit password
            while (PIN.size()!= 6)
            {
              std::cout<<"Your password must be 6-digit; please set up again.\n";
              std::cin>>PIN;
            }

            int ACCT=controller.open_account(PIN,KYC);//return the account number generated by the system;
            // since account number is randomly generated, if there are too many attempts to open the account, all generated account number
            // will be used up so that it returns 0; since the number of account numbers is very large, doing this will also avoid spammers attack
            if (ACCT == 0) std::cout << "No more account number available." << '\n';
            // print the account number generated, and it's balance is set to 0;
            else std::cout << "Your account is created, account number is:  "<< ACCT<< '\n';
        }

        // open deposit
        else if (customerInput == "DEPOSIT")
        {
            // If user is familiar with the procedure, they can input all requirement once together.
            // However, this program is intended as step by step instruction;
            std::cout << "please enter the account number you want to deposit to" << '\n';
            int ACCT; std::cin >> ACCT;
            std::cout << "please enter the amount of money" << '\n';
            int VALUE; std::cin >> VALUE;
            if(controller.deposit(ACCT,VALUE))
            // Print "Success" if deposit is received
            std::cout << "Success!" << '\n';
            // Our system is intended to prompt "system busy" message if the PIN or any input is not valid
            // By doing so, it is intended to protect user's information
            else std::cout << "System busy, try later" << '\n';
        }
        // openning deposit does not require password
        // As you can see, this system is intended that all users can access any account if PIN of the account is correct.
        // Different from ATM system, this project is like the backend of the bank
        // so that users in the system are like stuff of the bank

        // Withdraw money from the account.
        else if (customerInput == "WITHDRAW")
        {
            std::cout << "please enter the account number you want to withdraw from" << '\n';
            int ACCT; std::cin>>ACCT;
            std::cout << "please enter the amount of money" << '\n';
            int VALUE; std::cin>>VALUE;
            std::cout << "please enter your account PIN" << '\n';
            std::string PIN; std::cin>>PIN;
            if(controller.withdraw(ACCT,VALUE,PIN))
            std::cout << "Success!" << '\n';
            else std::cout << "System busy, try later" << '\n';
        }

        // Purchase from POS;
        else if (customerInput == "PURCHASE")
        {
            std::cout << "please enter the account number you want to purchase from" << '\n';
            int ACCT; std::cin >> ACCT;
            std::cout << "please enter the amount of money" << '\n';
            int VALUE; std::cin >> VALUE;
            std::cout << "please enter your account PIN" << '\n';
            std::string PIN; std::cin >> PIN;
            if(controller.purchase(ACCT,VALUE,PIN))
            std::cout << "Success!" << '\n';
            else std::cout << "System busy, try later" << '\n';
        }

        // Attemp a time deposit
        else if (customerInput == "TIME")
        {
          std::cout << "please enter the account number you want to attempt a time depost from" << '\n';
          int ACCT; std::cin >> ACCT;
          std::cout << "please enter the amount of money" << '\n';
          int VALUE; std::cin >> VALUE;
          std::cout << "please enter your account PIN" << '\n';
          std::string PIN; std::cin >> PIN;
          std::cout << "please enter the period in days" << '\n';
          int PERIOD; std::cin >> PERIOD;
          if(controller.time_deposit(ACCT,VALUE,PIN,PERIOD))
          std::cout << "Success!" << '\n';
          else std::cout << "System busy, try later" << '\n';
        }

        // Transfer money between accounts
        else if (customerInput == "TRANSFER")
        {
          std::cout << "please enter the account number you want to transfer from" << '\n';
          int ACCT_FROM; std::cin >> ACCT_FROM;
          std::cout << "please enter the account number you want to transfer to" << '\n';
          int ACCT_TO; std::cin >> ACCT_TO;
          std::cout << "please enter the amount of money" << '\n';
          int VALUE; std::cin >> VALUE;
          std::cout << "please enter your account PIN" << '\n';
          // only PIN of the account user transferrs from is needed
          std::string PIN; std::cin >> PIN;
          if(controller.transfer(ACCT_FROM,ACCT_TO
            ,VALUE,PIN))
          std::cout << "Success!" << '\n';
          else std::cout << "System busy, try later" << '\n';
        }

        // settle the interests;
        // this function is void so that nothing will be returned.
        // However, interests will be calculated in the backend.
        else if (customerInput == "SETTLE")
        {
          controller.settle();
          std::cout << "Interests of the day is settled,please check your balance." << '\n';
        }

        // Quiry for the balance
        else if (customerInput == "BALANCE")
        {
          std::cout << "please enter the account number you want to quiry" << '\n';
          int ACCT; std::cin>>ACCT;
          std::cout << "please enter your account PIN" << '\n';
          std::string PIN; std::cin>>PIN;
          // balance will return 0 if any users' input information is wrong;
          // so that users' information will be protected.
          std::cout<<controller.query_balance(ACCT,PIN) << std::endl;
        }

        // delete the account
        else if (customerInput == "CLOSE")
        {
          std::cout << "please enter the account number you want to close" << '\n';
          int ACCT; std::cin>>ACCT;
          std::cout << "please enter your account PIN" << '\n';
          std::string PIN; std::cin>>PIN;
          if(controller.close_account(ACCT,PIN))
          std::cout << "Success!" << '\n';
          else std::cout << "System busy, try later" << '\n';
        }

        // exit the system
        else if (customerInput == "EXIT")
        {
            std::cout << "Exiting the system" << '\n';
            exitedUser=true;
        }

        // the command is case sensitive so that any other type in will result to invalid command
        else {
            std::cout << "you did not enter a valid command. Try again." << '\n';
          }

        }
        controller.write();
      }


// to authenticate user if user's input matches
  void ACCOUNTING::authenticate()
  {
    std::cout<<("Entre your user name\n");
    std::string username;
    // database is stored with the username as the filename;
    // failing in finding the file is equivalent to failing in finding the username
    std::cin >> username;
    std::ifstream fin;
    fin.open(username);
    if (fin.fail())
    {
      std::cout<<"user not found\n";
      // exit the system if username is invalid.
      exit(1);
    }
    else
    {
      std::cout << ("Entre your PIN\n");// prompt for PIN
      std::string pinInput, pin;
      std::cin >> pinInput;
      fin >> pin;
      if (pin == pinInput) userAuthenticated = true;
      else
      {
        // userAuthenticated is still false so that loop will be continued
        std::cout<<"Invalid PIN.\n";
        // username will be required to be typed in again so that 
        // guessing the PIN is prevented by extra typing time and the result of exiting if username is invalid
      }
    }
    fin.close();

  }//end function authenticate
